#ifndef TETROMINO_TYPES_H
#define TETROMINO_TYPES_H
enum TETROMINO_TYPES
{
    TETROMINO_TYPE_NONE,
    TETROMINO_TYPE_O,
    TETROMINO_TYPE_T,
    TETROMINO_TYPE_I,
    TETROMINO_TYPE_L,
    TETROMINO_TYPE_J,
    TETROMINO_TYPE_Z,
    TETROMINO_TYPE_S,
    TETROMINO_TYPE_MAX
};
typedef enum TETROMINO_TYPES TetrominoType;
#endif